### ISSUE TITLE
Census view should always have the current row

### ISSUE THREAD

**Issue by vadz** [vadz/lmi#126]
Even if there is no selection, the row containing the cursor should be considered current, i.e. operations such as "Census|Edit cell..." etc should apply to it instead of being disabled.

**Comment by thesiv** [comment]
If some row is selected and the cursor is on some other row. Which row should be edited (current or selected)?

**Comment by vadz** [comment]
This was discussed in [this thread](https://lists.nongnu.org/archive/html/lmi/2019-06/msg00041.html) but I'm not sure if there was any definitive conclusion about this particular question. It might still be helpful to reread that thread.

I think that it makes sense to edit the row containing the current cell, but I also wonder if we couldn't avoid such situation in the first place, i.e. always keep the row containing the current cell selected if there are any other selected rows?

**Comment by thesiv** [comment]
We can't avoid such situation if we allow multiple selection:
1. Create a census with 3 rows.
2. Hold `Ctrl` and click by a cell from 1'st, then from 2'nd, then from 3'rd rows.
3. Hold `Ctrl` and click by a cell from 2'nd rows again.
Result: 1'st and 3'rd rows are selected, the cell from the 2'nd row is current.

Can we edit the record (current cell)? Can we delete the rows (will the row of the current cell deleted too)?

Is the delete operation should be enabled If there is no selection?

I read the thread.

VZ> 1. Use the current cell for all operations on an individual life, such
ZV>    as "Edit cell".

GC> Yes, I think that's the obvious way, and probably the only one
GC> that makes sense. And it's simple.

VZ> 2. Only allow row-based selection in wxGrid and use the selected rows,
VZ>    if any, or the current row, as determined by the current cell,
VZ>    otherwise, for the operations on multiple lives, such as "Delete".

GC> Okay.

**Comment by vadz** [comment]
Re "avoiding such situation": I thought that perhaps we could clear the selection if the user deselects the row containing the current cell. But this risks being complicated, and I'm not sure how useful would this really be anyhow, so let's not do this for now.

As the reply that you quoted says, let's just use the current cell for all operations on the individual cells (such as "Edit") and use the selected rows (which wouldn't necessarily include the current one) for the operations on multiple cells (such as "Delete").

**Comment by vadz** [comment]
Fixed in the latest version of #120, thanks.
